name: Update Contributions

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-contributions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Generate contribution graph
        env:
          GITHUB_USER: MohammedMaaz06
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/generate_contributions.py

      - name: Commit updated contribution graph
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/contributions.svg

          if git diff --cached --quiet; then
            echo "No contribution changes."
          else
            git commit -m "chore: update contribution graph"
            git push
          fi
